name: adhd_cleaning_support
description: A gentle cleaning companion designed to reduce task-initiation friction.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.0
  file_picker: ^10.3.3
  flutter_timezone: ^5.1.0
  shared_preferences: ^2.5.5
  timezone: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
